name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Login to Docker Hub
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - run: docker build -t pctapia/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true pctapia/react-test npm test -- --coverage

      # Build and push Docker images
      - name: Build and push Docker images
        run: |
          docker build -t pctapia/multi-client ./client
          docker build -t pctapia/multi-nginx ./nginx
          docker build -t pctapia/multi-server ./server
          docker build -t pctapia/multi-worker ./worker

          docker push pctapia/multi-client
          docker push pctapia/multi-nginx
          docker push pctapia/multi-server
          docker push pctapia/multi-worker

      #Deploy to AWS Elastic Beanstalk
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        #run: zip deploy.zip docker-compose.yml

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker-app
          environment_name: Multi-docker-app-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-927644637321
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
